# Generated by Django 3.0.5 on 2021-02-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_document', models.CharField(choices=[('01', 'DNI'), ('06', 'RUC')], default='01', max_length=2, verbose_name='Tipo Documento')),
                ('document', models.CharField(blank=True, max_length=15, null=True)),
                ('full_names', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
